### ISSUE TITLE
KerbalGPS : support for planner EC consumption + reliability

### ISSUE THREAD

**Issue by Gordon-Dry** [Kerbalism/Kerbalism#298]
Mod: KerbalGPS

Modules that consume EC:

- ModuleGPSTransmitter
- KerbalGPS

Reliability also needs to be implemented. ofc. Could have not mention it. Should be clear.

**Comment by lordcirth** [comment]
How does reliability consume EC?  Not sure what you mean.

**Comment by Gordon-Dry** [comment]
Oh man, I just wanted to say "please do not forget to also implement reliability for these modules" ...

**Comment by lordcirth** [comment]
Ah ok that makes more sense :)

**Comment by Gordon-Dry** [comment]
Yeah, I just put a plus sign in front of the word "reliability" and it was interpreted as a bullet point so it looked like a part of the list.

**Comment by SirMortimer** [comment]
There is a preliminary new part module that was done for exactly this purpose. Beware, I didn't test this, so I don't know if it works at all:

```
MODULE {
  name = KerbalismProcess
  ec_produced = 0 // EC produced by this part
  ec_consumed = 0 // EC consumed by this part
  resources_produced = Love@0.3,Light@1.2, ... // you get the picture
  resources_consumed = Aura@2.1, ... // you get the picture
  loaded = false // if true, also runs while the vessel is loaded
  unloaded = true // if true, also runs while the vessel is not loaded (background)
}
```

Rates are in units per second. All the fields are optional. So for a GPS thing that uses EC and nothing else, this would suffice:

```
MODULE {
  name = KerbalismProcess
  ec_consumed = 2
}
```

Again, this is absolutely and utterly untested.

**Comment by SirMortimer** [comment]
The way to do is to add some code to KerbalGPS that uses the Kerbalism API.

Since Kerbalism 3.2 there is a [part module API for resource consumption](https://github.com/Kerbalism/Kerbalism/wiki/TechGuide-~-Part-Module-API). Notification callbacks for failures have been in there for a bit longer:

https://github.com/Kerbalism/Kerbalism/blob/07527801243df881c682e684e31a9e93130c922c/src/Kerbalism/System/API.cs#L562-L597

For resource consumption, the part module needs to implement the Kerbalism interface (doesn't add a dependency, see wiki page above).

To add failures, add Kerbalisms Reliability module to the part, the mod would then have to register a listener via `KERBALISM.API.Failure.Add` and do whatever magic needs to happen on a part failure.

It needs to be done by KerbalGPS, I won't add this to Kerbalism.
