### ISSUE TITLE
Suggestion : Change How Reliability Works

### ISSUE THREAD

**Issue by SevenOfCarina** [Kerbalism/Kerbalism#355]
Yes, I understand this a heck of a lot to ask for, and that this'll probably never go through unless I somehow try and build it myself, but here goes :

Reliability as it works now depends on each part category having a mean time before failure, which can be increased by extreme over-engineering. While this makes perfect sense for parts like probe cores, batteries, life support systems, antennas, etc. that are expected to be in continuous use with very few, if any, breaks, it makes no sense for engines, reaction wheels, motors, and the like which are operational for very short time periods with long breaks in between. There's also a murky line for parts that do have long periods of intense activity interspersed with long idle periods, like ISRU units, and drills. 

What I'm suggesting now is simple : have a modifier that comes into effect when a part is in operation, which reduces mean time before failure by an appropriate amount. For example, an engine might have a mtbf of a year when idle, but when under full thrust, it might be more like one hour for a launch engine. I understand that it'll be very processor intensive to track every single part all the time, so it might work out better to have each module, say, modulereactionwheel, trigger the modifier when it is activated for a particular part, and trigger it again when it is deactivated. Not all modules need to be tracked too, probably only drills, converters, engines, and airlocks (pressurisation/depressurisation cycles).

Additionally, it'll be nice to specify mean time before failure for each part separately, allowing for clear distinctions between cheap, unreliable, early-game parts and high-quality late-game parts, or disposable and reusable engines. I'm utterly useless at coding, but I'm more than willing to help out with the config files, since that is something I can actually do.

It would also be appreciated if there was a way to boost reliability through the tech tree, with broad increases in component quality as knowledge advances across a particular branch, like command modules, or engines. This'll make career games more realistic, with the early game marred by frequent failures that add an element of difficulty. 

Thank you for reading this, and I totally understand if this isn't worth implementing for some reason or the other. I'd welcome ideas that'd allow at least some of these features without too much extra work.

**Comment by lordcirth** [comment]
Note that there are already multiple mods that do this sort of thing. BARIS, TestFlight, and DangIt come to mind. We may want to look into deduplicating effort here.

**Comment by SevenOfCarina** [comment]
Yeah, but Kerbalism is _incompatible_ with those. I suppose a patch is in order?

**Comment by lordcirth** [comment]
Is it really incompatible? If you turn Kerbalism's Reliability off in settings, are there still problems?

**Comment by SevenOfCarina** [comment]
I haven't really tried, TBH, I just trusted the warning on download. I'll take a look.

**Comment by Damien212** [comment]
As per discussion on discord:

Is it possible to have engine failure chance be based on actual burn time (possibly with a small long term  reliability degradation on top for long coast periods)? The idea is to enforce maximum rated burn time of engines in RO instead of having barely used engines fail just because they've been sitting a while, but can burn indefinitely otherwise.

Currently we (RO players) use Testflight to simulate engine reliability. Engines have a rated burn time which failure rate increases massively over, but failures/malfunctions can happen at any time. Reliability is improved by doing actual test flights, whereby you gain points for that particular engine which reduce its change of failure.

If engines could have a MTBF value measured in burn time instead of lifetime, and if spending extra on reliability gives you slightly more burn time/less chance of failure during an overburn it'd be useful.

The alternative is to allow us to exclude all engines from Kerbalism's reliability system so we can continue to use other engine reliability mods while still enjoying other part malfunctions.

**Comment by SirMortimer** [comment]
See also #424

**Comment by lordcirth** [comment]
If I remember correctly, Kerbalism's reliability worked by rolling a random failure date, then checking if we'd passed that date. I think it would be fairly easy to subtract X seconds from that date while the engine is loaded and running. If it's not loaded, it's not running, so the code doesn't need to run for inactive vessels.

**Comment by gotmachine** [comment]
I agree that the reliability system is not very good, I personally don't use it anymore.
While the concept of passive random failures related to a MTBF is somewhat accurate in some cases, it's very unrealistic for many things, as stated in this issue.
It's also annoying as hell because of the constant timewarp-stopping notifications, and the ability to hide them isn't satisfactory as you often **need** to be aware of them. The micromanagement of repairable failures is repetitive and boring : timewarp > a bunch of failures happen > switch to the vessels > fix > go back to what you were doing, repeat every time you timewarp.

As stated, there are several other plugins that offer a more more polished take on failures, they are perfectly compatible if you disable the reliability feature.

The current system, while having its limitations, has the benefit of being technically simple, reliable (!) and easy to maintain. It's simplicity makes it somewhat universally compatible with all partmodules, it require very little work to make it work with other partmodules from other mods.

I personally think it's a waste of dev time to expand on the current system, the effort would be better spent in doing better integration with other mods that do failures like BARIS for stock, or TestFlight for RO.

**Comment by SirMortimer** [comment]
There's been an update for reliability with engines - but engines only. Similar to what Testflight  does according to the description above, but without the possibility to improve engine ratings with tests. See https://github.com/Kerbalism/Kerbalism/wiki/TechGuide-~-PartModules-~-Reliability

As my feeling is that this is already stretching the scope of Kerbalism regarding reliability, I'm closing this issue because honestly I don't see much more happening. Anything that goes further should probably be done via integration with other mods, I'd be perfectly happy to add API functions regarding reliability if that is requested.
