### ISSUE TITLE
EVAs and Airlocks

### ISSUE THREAD

**Issue by UsernamesAreAlwaysTaken** [Kerbalism/Kerbalism#374]
Currently, as it stands, when you EVA, it removes 330 (i think) units of nitrogen, and everything is fine afterwards.

For realism purposes, if there's no dedicated airlock on the vessel, the entire ship should be vented. If airlock is present, then only the airlock should, or probably less, as they'd pump most of the atmosphere out of the airlock (a timer could be introduced, pumping atmo based on the volume of the part)

Suggestion: add a field in the Habitat module named airlock=true/false. If EVA is done from a part without an airlock, the entire ship gets vented, and then you'd have to re-pressurize everything.

If EVA is performed from a part with an airlock, only lose a certain amount of nitrogen/oxygen (78/22 ratio).

This approach would require patching some parts, adding the airlock field to them. I'm willing to do the patches.

**Comment by 3x01** [comment]
Rather than a specified airlock module, it should just vent the module the kerbal is exiting. They do have bulkheads, don't they?

**Comment by eberkain** [comment]
Venting the module a kerbal is leaving could be the default behavior.  But we could assume that a dedicated airlock module could depressurize and save 90% of its atmosphere, or in essence we could just flag airlock modules and if a kerbal is leaving a module with the flag you only loose 10% of the modules volume in resources instead of 100%.

**Comment by gotmachine** [comment]
See current rework of habitat : https://github.com/Kerbalism/Kerbalism/issues/480#issuecomment-583702268
Closing this issue.
