### ISSUE TITLE
max_pressure not working 

### ISSUE THREAD

**Issue by Standecco** [Kerbalism/Kerbalism#394]
I've determined that the "pressurized=no" tag doesn't actually affect stress buildup, so it's effectively broken. 6af755da97b0594392f038160cd20d631d3b1908 was supposed to fix this, but sadly it wasn't enough.

**Comment by SirMortimer** [comment]
I think I got it this time.

The way it works for now is this: a habitat can have a max_pressure setting (it is assumed to be 1 if not configured otherwise). The habitat pressure of the entire vessel will be the minimum available max_pressure of all habitats. So be careful when you dock a Mk-1 pod to a big station.

Please note: this is, for now, just relevant for the process modifiers. The actual atmosphere inside the capsule might very well be pressurized at 100kPa. So the capsule will not vent anything to space if it is over pressure, it just won't count as pressurized.
