### ISSUE TITLE
Preliminary DLC Compatibility

### ISSUE THREAD

**Issue by UsernamesAreAlwaysTaken** [Kerbalism/Kerbalism#395]
Preliminary testing, still trying to figure out the kinks.

Two possible options, depending on workload:

1: Leave as is. It's still timed science, but there would be 2 different systems (Squad's and ours). Not the end of the world, but MUH CONSISTENCY!

2: Plugin work, probably a whole bunch of it. 

 So far:

- A new module will probably be required to replicate squad's functionality. So far, the functionality is power consumption, power generated, placement rotation axis and a distance curve. I'm still not exactly sure how all the science functionality is done via only these fields. Animations are in a separate module, ModuleAnimationGroup.

- Integration with other new custom modules introduced by Squad. There's the central station, comms, generic deployable parts. It's wizardry to me, so needs sorting out. Either integration, or, again, new modules (maybe same module as the one above, but with extended functionality. I don't know).

- There's a bunch of "anomalies" or surface features defined in \Kerbal Space Program\GameData\SquadExpansion\Serenity\Resources\rocsdef.cfg. Someone will have to code restrictions/requirements for these features, for experiments to be able to be performed only when in close proximity to these specific features, and call back on the proper experiment definition accoding to the feature.

- The aids one: The Robot Arm Scanner. The part itself has a single experimentID = ROCScience, but then it somehow uses different experiment definitions based on where the experiment is done. ScienceDefs.cfg has unique EXPERIMENT_DEFINITIONs for every single "anomaly" on each body, and this experiment uses that particular definition to calculate science value (essentially running a different experiment) based on which feature/anomaly is scanned. 

Example of EXPERIMENT_DEFINITIONs (just the ids are copied):
id = ROCScience_EelooBerg
id = ROCScience_LaytheGeyser
id = ROCScience_MunLargeCrater

and so on, you get the idea.
Whatever is after `_` is basically the feature. All this in a few words: Single experiment, with custom values for each anomaly. Ideally, have a single experiment definition to avoid all the spam (if possible) and be able to give the experiment a different baseValue based on which anomaly is scanned. Otherwise we need the same implementation (Experiment with one experiment_id, but then be able to use different EXPERIMENT_DEFINITION based on where the experiment is done). 

Secondary option is to add all of these experiments on the parts, and only make them visible (button only appears) when conditions are met (there was a hide when unavailable field somewhere in the Experiment). Dirty, but functional (this only fixes the last bullet point. The first 3 still need taken care of. I'd still preffer a cleaner approach).

Have fun gents. This is just at a first glance, I doubt we'll get away with it that easily. More stuff is bound to pop up, as per usual.

P.S: Patching this shit is stupidly easy, no mental gymnastics required. Plugin work on the other hand...

**Comment by gotmachine** [comment]
What do we want actually ? The way those experiment works does not conflict much with the new Kerbalism science. I see only a few things that somewhat doesn't line up. Most annoying first :

1. Surface experiments transmission rates ignores Kerbalism data rates
2. Surface experiments produce data that isn't stored on a drive and cannot be transferred while in EVA
3. Surface experiments power generation/consumption is super simplistic (just put enough power units)
4. The robot arm scanner is producing science instantly, instead of over time. Currently it should work just fine with the current Kerbalism version (should put its data on our drives).

Now a general remark about surface experiments : the stock code is quite complex because it actually implement a full standalone background processing solution. We may be able to somehow hook into it to put a bit of functionality on top but altering the core functionality is impossible and trying to replicate it from scratch is gonna be quite some work.

Points 1 and 2 can maybe be patched by adding our drive and a classic antenna module to the controller part, and redirecting the data generated by the stock system.

Point 3 is harder. We could maybe do it by using a dummy EC generator on the controller that output power based on the presence of the stock solar panel / RTG in the cluster, that would allow to have EC generation for our antenna. But that would be on top of the (simple) stock power system, I'm not sure there is any benefit in doing that because the experiments would still use the simple stock system.

Point 4 can maybe be patched be deriving a module from the stock module, saving the "rocInRange" to do data sampling in the background. But I'm not sure there is any benefit in doing so. While the "over time" thing make sense in a lot of case where the stock system is too basic / doesn't fit well, this one actually require driving a rover manually to find a surface feature. It's quite involving for the player and there isn't much a point of making the experiment take time to be performed.

**Comment by SirMortimer** [comment]
1+2: we already have the ability to grab whatever data is generated and put them on one of our hard drives on the control station thingy. I'll be looking into how to get that data OFF that thing again, which will probably be done with a custom implementation for control station comms (it needs to look at the cluster, search for antenna, and use that for transmission).

I wouldn't worry about the power issue (3) for now. I mean, don't just ignore it, but I think it might be too soon to do something Kerbalism specific here. Any game mechanic we change here will have to be redone for upcoming mods that will contribute their own surface samples. IMO it could be best to just wait and see what happens, until then leave it as it is.

And I'm fine with robot arms providing instant science, for the reasons stated above.

**Comment by SirMortimer** [comment]
I think this done, aside from a couple of necessary config tweaks that will eventually surface.
