### ISSUE TITLE
Release and distribution changes (Spacedock, CKAN...)

### ISSUE THREAD

**Issue by theJesuit** [Kerbalism/Kerbalism#420]
This is a request to mirror what is happening on CKAN on Spacedock, to allow manual installs to be more straight forward without asking users to delete folders or alter setting.cfg.

This would mirror Kopernicus.  The code is separately installed to planet packs.

**Comment by gotmachine** [comment]
We are (@UsernamesAreAlwaysTaken ?) in the process of finalizing the move of all the config files (including the support folder and the parts) to KerbalismConfig, in order to avoid any unwanted interaction between kerbalism-core and third party config packs.

About Spacedock, we will put the 2 separate zips in the download (same zips as the GitHub releases) instead of an already merged GameData. We could also put a dummy file at the root of the zip, named "Don't install Kerbalism-Config if you are using a third-party config pack". I think that should be idiot-proof enough.

What I fear with having 2 separate downloads on Spacedock is that it would result in the inverse situation, where people only download and install the configs or the core mod and wonder why it doesn't work.

**Comment by gotmachine** [comment]
Note on what we need to do to switch CKAn to the github releases :
  - Use github in the kref, with a regexp match to core/config zips (see https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md#ckangithubuserrepoasset_matchfilter_regexp)
  - Remove the "install" directives at the end of the file

**Comment by SirMortimer** [comment]
see https://github.com/KSP-CKAN/NetKAN/pull/7374

**Comment by gotmachine** [comment]
Still to do 
[ ] : add the "dummy files for dummies" in the zips (build system)
[ ] : Spacedock release uploading automation (?)
