### ISSUE TITLE
Feature Request - Probe Core Radiation Damage

### ISSUE THREAD

**Issue by Damien212** [Kerbalism/Kerbalism#424]
As discussed on discord:

As we currently have to consider radiation when sending manned missions, the same should be true for unmanned missions. 

Probe cores should suffer radiation damage that affects MTBF and other effects such as reduced science collection/transmission, and HDD capacity reduction (bad sectors). Damage should build up over time and can be mitigated by shielding, higher quality electronics and planning trajectories to minimise the time spent in radiation belts.

Radiation damage MTBF effects could also be added to all other electronic parts (experiments, batteries etc) to a lesser extent.

Hibernation could also be used to prevent damage. Hibernation on/off can be an automation option for high/low rad levels (maybe with a configurable strength level?) to reduce micromanagement.

**Comment by lordcirth** [comment]
I am not convinced of this. Probes have a number of limitations compared to crewed missions, in exchange for being exempt from life support concerns. Making probes more difficult will particularly impact players using Probes Before Crew such as myself.

**Comment by Damien212** [comment]
> I am not convinced of this. Probes have a number of limitations compared to crewed missions, in exchange for being exempt from life support concerns. Making probes more difficult will particularly impact players using Probes Before Crew such as myself.

It'll only affect probes in high radiation areas and only in so much as it affects MTBF. It can be mitigated by trajectory considerations and shielding. It would also have to be balanced so as not to be too difficult.

**Comment by Gordon-Dry** [comment]
Well, this can be a toggleable difficulty setting.

**Comment by gotmachine** [comment]
I'm also not convinced. Kerbalism already add a lot of variables, this seem like an unneeded and annoying complication.
If you have played a lot with it, you already know : 
- the time spent in mission planning to get things right
- the time spent doing part/vessel tweaking and micromanagement
- the high ratio of mission failure due to unexpected / misunderstood requirements. 
A lot of the Kerbalism features, while realism oriented, are implemented as much as possible in a simple "buff-debuff" way (radiation > shielding, stress > hab space, reliability > low/high quality). Complex features with many variables are hard to expose clearly to the player, hard to balance properly and are often not very fun to play with. Do you really want to have to tweak the radiation shielding of every probe, hard drive, battery ?

Remember that a realistic simulation is not achievable technically, nor desirable. What is desirable is a feature that is meant to be **played** with while being a good **approximation** of the reality.

Also, on a technical note, I'm not inclined to see any more feature being added that rely on environment conditions like radiation until there is a proper fix to the high timewarp speeds evaluation inconsistencies.

**Comment by SirMortimer** [comment]
I'd rather do that in an external mod.
