### ISSUE TITLE
Rational Resources support

### ISSUE THREAD

**Issue by ghost** [Kerbalism/Kerbalism#427]
https://forum.kerbalspaceprogram.com/index.php?/topic/184875-rational-resources-v085-jun-11-2019/

![](https://img.steamport.xyz/1560365074.png)

**Comment by gotmachine** [comment]
https://github.com/Kerbalism/Kerbalism/issues/16#issuecomment-522243869

**Comment by gotmachine** [comment]
Reporting JadeOfMaar comment :
Hello, gents. Rational Resources was built with life support mods (particularly Kerbalism) in mind. And it's very easy (requiring little effort) to make any planet pack compatible but at the cost of rapidly inflating the MM cache due to the level of precision that Rational Resources boasts. 

I've just added documentation concerning the split mods [here](https://github.com/JadeOfMaar/RationalResources/wiki#mods) (thanks for drawing attention to that @todi ) and you can read about the templates and see how easy it is to setup a planet pack [here](https://github.com/JadeOfMaar/RationalResources/wiki/Templates).

@gotmachine Concerning the issue of redundant, incompatible patches, I was personally told by/I agreed with the Kerbalism devs that once RR's ISRU chains were finalized, their figures would be ported over to Kerbalism's style of converter configs and mine would stop themselves from running when Kerbalism is present.

**Comment by SirMortimer** [comment]
Referencing #16 here so the connex doesn't get lost

**Comment by SirMortimer** [comment]
Take a look at https://github.com/JadeOfMaar/RationalResources/blob/master/GameData/RationalResourcesParts/CRP/zKerbalism.cfg
> I've mostly setup Rational Resources drill and converter patches for Kerbalism. All I ask of you guys is to scale down the numbers in the Process{} nodes at the bottom of this file, and well, let me know if any syntax is bad or missing

**Comment by gotmachine** [comment]
As far as I know, RR now implements full support for Kerbalism.
