### ISSUE TITLE
StackOverflowException with CommNet Constellation

### ISSUE THREAD

**Issue by SirMortimer** [Kerbalism/Kerbalism#439]
From the forums, https://forum.kerbalspaceprogram.com/index.php?/topic/172400-140-171-kerbalism-v302/page/74/&tab=comments#comment-3621354

> When CommNet Constellation is running with Kerbalism, anytime I view the tracking station or launch another vessel, the game hard crashes and dumps the error to the log.

```
[EXC 19:27:13.192] StackOverflowException: The requested operation caused a stack overflow.
    KERBALISM.Vessel_info..ctor (.Vessel v, Guid vessel_id, UInt64 inc)
    KERBALISM.Cache.VesselInfo (.Vessel v)
    KERBALISM.AntennaInfoCommNet.Init ()
    KERBALISM.AntennaInfoCommNet.AntennaInfo ()
    KERBALISM.ConnectionInfo.GetAntennaInfo (.Vessel v, Boolean powered, Boolean storm)
    KERBALISM.ConnectionInfo..ctor (.Vessel v, Boolean powered, Boolean storm)
    KERBALISM.ConnectionInfo.Update (.Vessel v, Boolean powered, Boolean storm)
    KERBALISM.Vessel_info..ctor (.Vessel v, Guid vessel_id, UInt64 inc)
    KERBALISM.Cache.VesselInfo (.Vessel v)
    KERBALISM.AntennaInfoCommNet.Init ()
    KERBALISM.AntennaInfoCommNet.AntennaInfo ()```

**Comment by dskzz** [comment]
I got this error in a playthrough.  It's strange though.   Only happens on a single design, a probe with those 2 cloverleaf relays, a dish relay, a SLIM probe core and on the lifter an octo core with that sideways communicatron.  I tried launching the same craft in a game with stripped down mods and in sandbox mode in the heavy modded version that crashed in career mode.  It did not crash in sandbox mode.  I'd be happy to send you the save file and the details if you want!

**Comment by gotmachine** [comment]
Following https://github.com/Kerbalism/Kerbalism/commit/1f108c1a0bb305f44291e366a5ce09f52da57946   I think this is fixed in the dev branch as a side effect of the vessel_info refactor, since vessel_info has been merged in VesselData.

The root cause of this is 
- ConnectionInfo.Update request vessel_info
- vessel_info ctor is called and call ConnectionInfo.Update
- wich in turn call the vessel_info ctor
And so on until a stackoverflow exception happen

Since now (in the dev branch) VesselData is never destroyed like vessel_info (it was recreated on-demand), this should not happen anymore.

Please playtest [the latest dev build](https://github.com/Kerbalism/DevBuilds/releases) (make a backup of you save before) and try to reproduce the issue, and let us know if its fixed.

**Comment by gotmachine** [comment]
@dskzz The 7167 build was broken, please test again with the 7168 build.

**Comment by gotmachine** [comment]
So this seems fixed. Keeping this open until next release.

**Comment by dskzz** [comment]
This hit again on the release version

**Comment by SirMortimer** [comment]
It's not fixed in the release version. The fix is in the current dev release.
