### ISSUE TITLE
More reliable/useable experiment automatic mode

### ISSUE THREAD

**Issue by infoman** [Kerbalism/Kerbalism#446]
I have a Goo canister with 3 available samples and want to disable it after a first run so it doesn't consume the remaining 2 accidentally. But the default option when I click on the part menu is to force re-running the experiment, so I went to the Auto tab and set it to turn off by action group 2. But instead it started to run again anyways.

**Comment by gotmachine** [comment]
For reference, thoses comments are still mostly valid : https://github.com/Kerbalism/Kerbalism/issues/404#issuecomment-498954935

**Comment by gotmachine** [comment]
#459 is essentially the same issue  (merging things here) : 

Moving samples into the container causes the experiments to run again : 

To reproduce: Launch a craft with a 2 material bays and an experiment storage unit. Run the mat bay until it's done. Move samples into the container using "Move data here". The mat bay starts collecting duplicate data into it's own storage all over again.

**Workaround** : Switching experiments to manual mode (instead of smart mode) in the settings can help.
