### ISSUE TITLE
UI for resource production/consumption

### ISSUE THREAD

**Issue by SirMortimer** [Kerbalism/Kerbalism#449]
We really should have an UI that tells you where resources are produced and consumed. Something like in the planner, but for in-flight instead. Broken down into several categories (like comms, experiments, habitats, younameit) so you know how much turning something on or off would change.

Example situation: you're in a pinch because you messed up and have an Mk-1 pod in Kerbins shadow for at least 4 hours. You don't have a fuel cell, and your batteries are draining fast.
What uses the most EC, what can be turned off and how much time would that buy me?

**Comment by gotmachine** [comment]
Maybe we could push this a step further. We have a lot of things that are managed vessel-wide, both internally and in practice. 
I'm thinking that moving the info and ui from the parts PAW to a common centralized UI would be better in every way :
- Managing processes "output level" globally, as a tweakable vessel-wide percentage instead of per-part, with visualization of resulting rates/ETA to depletion.
- Same for valve settings (fix for #422)
- Could possibly be an extended, unified version of the current vessel info thing (with automation, file manager...)
- Save/load of presets, autosave/restore presets after docking/undocking events based on vessel name (see #144)
The current in-flight panel is in need of a revamp anyway. Maybe this can be a part of the larger refactor on the horizon (#426)

**Comment by gotmachine** [comment]
Partial fix implemented in dev, consumers/producers in the supplies section, see https://github.com/Kerbalism/Kerbalism/commit/fef5a0d5fb030657361a6da25f4466fe0cc27b95

![image](https://user-images.githubusercontent.com/24925209/63213451-c6c3cd80-c10c-11e9-803f-cd30435c2ba4.png)

**Comment by SirMortimer** [comment]
That's exactly what I had in mind. Closing this issue as the implementation pretty much covers the scope of it.
