### ISSUE TITLE
Changing drill type with symmetry breaks GUI, nullrefs

### ISSUE THREAD

**Issue by TheDestroyerKSP** [Kerbalism/Kerbalism#457]
https://i.imgur.com/9uKGe1v.png

Steps to reproduce:

- Go into VAB/SPH

- Place a root part (command pod)

- Place a drill with symmetry

- Configure the drill, change it multiple times.

KSP log:

https://www.dropbox.com/s/7n73vnqupdtmu5m/KSP.log?dl=0

**Comment by gotmachine** [comment]
For reference, the exception is : 
```
[EXC 22:29:52.339] NullReferenceException: Object reference not set to an instance of an object
	UIPartActionResourceItem.SetSymCounterpartsAmount (Double amount)
	UIPartActionResourceEditor.onSliderChangeProcess ()
	UIPartActionResourceEditor.Setup (.UIPartActionWindow window, .Part part, UI_Scene scene, .UI_Control control, .PartResource resource)
	UIPartActionWindow.AddResourceEditorControl (.PartResource r)
	UIPartActionWindow.SetupResourceControls (.PartResource r, Boolean clearFirst, UI_Scene scene, System.Int32& controlIndex)
	UIPartActionWindow.CreatePartList (Boolean clearFirst)
	UIPartActionWindow.UpdateWindow ()
	UIPartActionController.UpdateActiveWindows ()
	UIPartActionController.UpdateEditor ()
	UIPartActionController.Update ()
```

This happen because it isn't possible to have symmetric parts with different resources on it. Stock synchronize the resource amounts between symmetry counterparts when you use the amount tweakable, and it actively watch that every frame. Now it seems that it only does it IF the resource is tweakable.

So the change introduced by this commit : https://github.com/Kerbalism/Kerbalism/commit/9d1952be96019b7fb8949694623fbe548ec86237 goes directly against that, allowing trough a `symmetric` config boolean in the configure module to not synchronize symmetry counterparts when configuring. Note that the default value is false, for "not synchronize".

Now in practice, the issue is most visible with the drill as it's the only part that : 
- can be surface attached (much more likely to be used in symmetry)
- has the default `symmetric = false` value
- has a switchable, visible and tweakable resources on it

The kerbalism tanks and containers all have `symmetric = true`, so they aren't affected.

But : 
- Non-surface attachable parts can also be used in symmetry.
- A lot of parts have the default `symmetric = false` and can switch visible resources (ex : waste processor add some waste capacity).

Example, put 2 MK-1 pods in symmetry and switch the last option until you get the waste processor : 
![image](https://user-images.githubusercontent.com/24925209/63218167-6c029400-c155-11e9-84e1-6b66352e4ded.png)

Now, either we : 
- Revert the changes made in the commit and force configure symmetry. Not good
- Break the symmetry if a tweakable/visible resource is switched, but prompt the player beforehand (as breaking symmetry can be a VERY annoying thing), letting him choose between not applying the configuration change or applying it and breaking the symmetry.

Breaking symmetry is achieved trough the EditorLogic.deleteSymmetryParts(Part) method. (remainder to myself)

**Comment by SirMortimer** [comment]
Don't waste your time on this: removing a part from a symmetry group is a stock function in 1.7, I think it was introduced in 1.7.2 but don't quote me on this. I think it's the same functionality.

So
> Revert the changes made in the commit and force configure symmetry. Not good
might indeed be the best option.

**Comment by gotmachine** [comment]
Nice, wasn't aware of that new PAW option. 

Well I did a middle ground thing, automatically break the symmetry to avoid the bug, notify the player. The player can always CTRL-Z to undo that.

I added a `TODO:` comment so we remember to remove the whole symmetric option when we drop support for older versions.
