### ISSUE TITLE
Science not stored even with space available

### ISSUE THREAD

**Issue by traisjames** [Kerbalism/Kerbalism#475]
<img width="1119" alt="Screen Shot 2019-07-28 at 12 56 40 AM" src="https://user-images.githubusercontent.com/751219/62011593-d9676a00-b13f-11e9-8fe9-6936c07477d7.png">
While trying to collect samples I get messages that there is not enough space on the hard drive, the data size listed is 4 Mb, and I have about 9 Mb of space free.

**Comment by gotmachine** [comment]
Probably something wrong with your install. 

Gravity Scan is not supposed to be a sample, and the likely reason why you can't store the data is probably because you are doing it from the stock experiment window, which is also not normal (I think). Those two facts make me believe you are missing some configuration files.

**Comment by gotmachine** [comment]
Maybe related, reported by @Sumguy#8076 on discord (https://discordapp.com/channels/418222516386004992/418222516386004994/609475700910718976)

Same issue : stock experiments done trough the stock module, can't be stored because hard drives are too small. The parts have a bunch of ModuleScienceExperiment/ModuleScienceContainer/DMModuleScienceAnimate using the stock experiments

See attached ModuleManager.ConfigCache : https://cdn.discordapp.com/attachments/418222516386004994/609478115215015937/ModuleManager.ConfigCache.zip

**Comment by UsernamesAreAlwaysTaken** [comment]
That config cache is just.... Like what the...

Basically. Half the experiments aren;t even patched, although they should (i run global searches for specific experimentIDs, which looking at the modules, they should have been caught by the global replacements). The experiments are either added later, or something interferes with the patching process. I mean, there's 224 instances of "experimentID" in that config cache, where there should be close to zero (unless custom experiments, which they're not)

I'd need a MM Log, or a KSP Log to figure out why.

As for this case in particular, @gotmachine you know about the xmitDataScalar. It's a sample, and the Gravity Scan has a pretty large dataScale, therefore, needs a ton of "slots". This is the most likely cause.

If these issues keep popping up, i'll look into redoing the patching process for the experiments. I made some assumptions regarding how configs SHOULD be written (mostly common sense, but apparently it's not that common), and that's getting screwed somewhere.

**Comment by UsernamesAreAlwaysTaken** [comment]
...
Found the problem regarding the MMConfigCache. 
That config cache has 16 instances of "experiment_id" (which is ours). Guess what are they?
`experiment_id = RP0-LiquidsMicrogravity`
`experiment_id = RP0-VisualTracking`
and so on. You get the idea.

In short:

MAKE SURE YOU USE THE PROPER CONFIG PACK.
That config pack was made for RP-0/RSS/RO/Whatever. I have no idea what Standecco did regarding stock/modded experiments, but apparently his nuke wasn;t thorough enough.
