### ISSUE TITLE
Tarsier Space Technology photos count as a "sample"

### ISSUE THREAD

**Issue by Tonas1997** [Kerbalism/Kerbalism#486]
![screenshot88](https://user-images.githubusercontent.com/43859708/63037423-05604a80-beb7-11e9-9d6b-c2ea62702852.png)

As shown on the screenshot, photos taken by TST telescopes are considered a "sample" and are, therefore, untransmittable. Could this be fixed via MM patching?

**Comment by UsernamesAreAlwaysTaken** [comment]
Yes. The experiment itself is not patched, thus you get the stock science dialogue window.

I assume there's a penalty in tranmission on the experiment, thus kerbalism considers it a sample.

**Comment by gotmachine** [comment]
This issue has already come a few times.

I think we should change what is considered a sample for the stock experiments.
We can't aim for 100% support of all mods, the fallbacks must be at least playable.

Currently, if xmitdatascalar < 0.666 the experiment is considered a sample.

https://github.com/Kerbalism/Kerbalism/blob/a0df2935c57fe139b58e9e40314254df1b98719e/src/Kerbalism/Science/Hijacker.cs#L264

I suggest we change this value something very low. 0,1 would be fine IMO. Better have sample be considered as files than the other way.

**Comment by UsernamesAreAlwaysTaken** [comment]
can you set it to 0?
Only consider it a sample when you cannot transmit it?

**Comment by gotmachine** [comment]
Yup, that's possible. Should I ?

**Comment by UsernamesAreAlwaysTaken** [comment]
yes please

**Comment by Tonas1997** [comment]
Changing `xmitDataScalar` to 1 wasn't enough, as expected. In the meanwhile, is there a way to make TST's "Take Picture" experiment compatible with Kerbalism?

**Comment by UsernamesAreAlwaysTaken** [comment]
Thing is, because this is a snowflake (this is what I call stuff that's done in an unusual way), there will be loss of functionality.

Generally, when patching mods, specifically science, I try to recreate the functionality with Kerbalism's tools as best as I can, to respect the modder's intention. With stuff like this, I have 2 options:
1.Leave it as it is, and have it return instant science (tbh makes sense, because you manually take the picture, all you have to do is transmit), with some rebalancing in mind.
2: Patch the experiment, transforming it into the stock telescope, which then there's no point installing the mod. This functionality cannot be replicated with what we have right now, and probably never will.

I'm definitely leaning towards 1, with some minor tweaks.

**Comment by Tonas1997** [comment]
> I'm definitely leaning towards 1, with some minor tweaks.

Agreed. Unless they are crazy enough to implement telescope integration times (!) an instant science result is the way to go.
