### ISSUE TITLE
Multiple Antenna Bandwidth/Range

### ISSUE THREAD

**Issue by UsernamesAreAlwaysTaken** [Kerbalism/Kerbalism#487]
Currently, spamming antennas on a vessel does little in terms of performance (range and bandwidth).

I propose that to be changed, or at least tweaked.

Make it somewhat more worthwhile installing multiple antennas on a vessel besides redundancy.
Increase bandwidth gains, and range gains, with a steep dropoff proportional to the number of antennas.

E.G: 1 antenna: 100% bandwidth and range (before range dropoff)
2 antennas: 180% bandwidth and 130% range
3: 210, 140
etc.

This is just an example. Numbers pulled from you know where, to illustrate better what I'm asking for.

**Comment by gotmachine** [comment]
The effect of combining antennas on  is controlled by CommNet, and tweakable trough configs. The formula is [on the wiki](https://wiki.kerbalspaceprogram.com/wiki/CommNet#Combining_antennas).

Some antennas are combineable, others not, I think there is a config switch for that. The effect of combining is controlled by the `antennaCombinableExponent` config value, default is 0.75.

It seems to me that tweaking that will also affect signal strength, which we base our data rate calcs on.

**Comment by SirMortimer** [comment]
There is a generalized relationship between transmission speed and distance.  All other things equal, you can talk half as fast from 40% (sqrt 2) further away.  So if you "combine" a second antenna that is the same as the original, you can either talk twice as fast (think of it as being on a separate channel), or you can talk at the same speed 1.4x as distant.

Since we're stuck with KSP saying that combined antennae yield extended range, I assume that they use an equation that maximizes the range at the cost of no speed gain - which is reasonable, because stock KSP never cared much about speed.

So, if combined antennae should give a non-marginal gain in range, the best we can do is massage the numbers for KSP to extend the range (``antennaCombinableExponent``) and take whatever transmission speed we get from that. But I don't think that we really can justify to increase speed AND range.
