### ISSUE TITLE
Add background processing compatibility (like RealBattery for example).

### ISSUE THREAD

**Issue by Gordon-Dry** [Kerbalism/Kerbalism#50]
Every attempt of non-physics timewarping could kill a crew because StoredCharge processing by RealBattery is not implemented.
Also other mod's background processing is affected (not taken into account by Kerbalism) as I've read in the forum thread.

**Comment by Gordon-Dry** [comment]
Just as a reminder:
https://forum.kerbalspaceprogram.com/index.php?/topic/151164-14x-real-battery-v141/&do=findComment&comment=3115816

https://github.com/ChrisAdderley/DynamicBatteryStorage/tree/master/Source/DynamicBatteryStorage

**Comment by SirMortimer** [comment]
If every attempt of non-physics timewarping could kill a crew that would be a bug in Kerbalism that needed to be fixed in Kerbalism and not fixed by implementing stuff for other mods that a user might or might not have installed.

Besides, if more than 1 mod is handling background processing, stuff is supposed to go haywire because the mods don't know of each other.
