### ISSUE TITLE
Realism Overhaul command parts draw incorrect power in background

### ISSUE THREAD

**Issue by SillySMS** [Kerbalism/Kerbalism#503]
Hello,

As has been discussed (primarily on the RO Discord), Realism Overhaul command parts are drawing incorrect power in the background. What I believe is going on:

1. Kerbalism polls each ModuleCommand for its EC consumption rate (and, in theory, any other resources).
2. In the foreground, RO's ModuleAvionics dynamically sets this rate. For some parts, it's always ModuleAvionics.enabledkW. For others, however, there is also a ModuleAvionics.disabledkW that corresponds to a "sleeping" state where it's still alive, but cannot steer any tonnage.
3. In the background, the rate is just pulled straight from the ModuleCommand config with no input from ModuleAvionics.
4. As a result, there is often incorrect power draw for unloaded vessels. Procedural avionics produce zero draw, relying entirely on ModuleAvionics to set things in the foreground, whereas many non-procedural parts, such as the early controllable core, produce too much draw, because their ModuleCommand's electricity rate is at the enabledkW rate.

What would be most elegant as I see it:
1. Either Kerbalism or a third-party plugin defines a "ModuleCommandDynamicBackground" which extends ModuleCommand, but persists a value (let's call it backgroundDraw) corresponding to the target background draw.
2. Kerbalism, when processing command parts, has special processing for any instances of ModuleCommandDynamicBackground to enable use of a low-power mode.
3. Either a patch is added to RO/RO-Kerbalism to change all its ModuleCommand to MCDB, or the ModuleAvionics plugin replaces MC with MCDB. Regardless of how it's done, the new MCDB sets the persisted backgroundDraw to be equal to ModuleAvionics's disabledkW.

**Comment by gotmachine** [comment]
We won't create a whole partmodule just for that.

Honestly the problem here is that ModuleAvionics is badly implemented. Unless there is good reason to do so, you don't hack a partmodule from another partmodule to extend it's functionality, you do a derived partmodule and you MM-replace the original in the configs.

Now, to stay constructive, to solve this  we just need the `currentWatts` KSPField to be made `isPersistant = true` here : https://github.com/KSP-RO/RP-0/blob/master/Source/Avionics/ModuleAvionics.cs#L20

Once we have that that will just require a regular background process patch from Kerbalism side for ModuleAvionics. 

ModuleCommand will still do it's possibly incorrect EC consumption so from the ModuleAvionics background method we need to :
- get the ModuleCommand module on the part prefab
- "undo" its EC consumption by re-producing it
- consume EC based on the proto ModuleAvionics persisted `currentWatts`

**Comment by gotmachine** [comment]
Further note : to solve this in a bit cleaner way, I would suggest that ModuleAvionics does the EC consumption by itself and MM patch the ModuleCommand EC rates to zero, instead of hacking it at runtime. That would be much simpler and cleaner for all parties involved.

**Comment by SirMortimer** [comment]
This reminds me of the plan we discussed once to pimp the ProcessController to something that could essentially run processes in Kerbalism that exist only from the part modules configuration (currently they need a separate process definition).

A generic part module that

* produces/consumes resources in foreground and/or in background
* read variables from another part modules persisted state to control the process (enabled/disabled, rate)

That way we wouldn't need new code in Kerbalism that is dedicated to a very specific part module with possibly changing variable names in future versions of it. I think there would even be a few part modules that currently have dedicated code in Background.cs that could be covered by that.

**Comment by gotmachine** [comment]
Yup I've given some thoughts about that, too. But in the end I'm not sure the "generic partmodule" is a good idea. In the end the mod author would still need to add code to its partmodule for it to not use the stock consumption/production methods. 

And for background consumption the partmodule would still need to expose the right persisted fields, so that require some code changes as well. 

I think going the API way is better, allowing people to use the Produce/Consume/Recipe methods directly, and to be able to define a static backgroundUpdate method in their partmodule. We can provide an easy to use wrapper for all that and store the methods in funcs to avoid the performance impact of reflection.

**Comment by SirMortimer** [comment]
So, it will be static functions in part module implementations, as outlined in #504
