### ISSUE TITLE
Comms API change for RealAntennas

### ISSUE THREAD

**Issue by gotmachine** [Kerbalism/Kerbalism#526]
Add to Comms API and base comm info class a 'ec / MB transmitted" in addition to the base EC rate (for RA support but could be used in the stock implementation too). Would be consumed in Science.Update().

**Comment by SirMortimer** [comment]
- extended the API so that it now knows ``ec`` and ``ec_idle``
- used the same logic in the stock commnet implementation

<img width="363" alt="idle_pwer" src="https://user-images.githubusercontent.com/43166475/69462472-61b9ec80-0d79-11ea-8397-73ad947ed9a3.png">

**Comment by Gordon-Dry** [comment]
As I was in a chat with DRVeyl about adding a RealAntenna to a kerbalEVA, I got the information that "Kerbalism is not RA aware for the planner yet, and just adding that controller will not be sufficient".

I stumbled upon this because I needed to add a dummy ModuleDataTransmitter to the kerbalEVA first so that Kerbalism sees it and patches accordingly.
RealAntennas normally got dedicated patches for specific parts with antennas or generic patches - checking for ModuleDataTransmitter.
As kerbalEVA normally got no antenna, this dummy patch is needed.

So I add a humble request to have Kerbalism natively check for ModuleRealAntenna and adding Reliability and PlannerController to those parts.
