### ISSUE TITLE
In flight the EC consumption popop over "supplies / electric charge" flickers the line for "other"

### ISSUE THREAD

**Issue by Gordon-Dry** [Kerbalism/Kerbalism#552]
I was reentering a pod, using the stock SAS holding retrograde.

This readout:
![Screen-2019-12-02_03-29-41](https://user-images.githubusercontent.com/29145213/69926274-18257c00-14b4-11ea-96e4-d7e2cb703e44.jpg)
- the frames the reaction wheel is used "other" is shown
- the frames the reaction wheel is not used "other" is not shown

This results in a rapidly flickering line for "other" when SAS retrograde is enabled.

My suggestion:
Have a cooldown timer for (all) lines to be still shown, also when there is no consumption.
Like 5 seconds.
In this case the readout for "other" would show "none" instead of the consumption value.
If the reaction wheel is used again within this cooldown time the line "other" is already there and the readout changes from "none" to the consumption value again.
No more rapidly flickering the readout.

**Comment by gotmachine** [comment]
Well I agree it's would be ideal to not have things flicker.
But that is a bit messy to do in the current state of things, the resource readout is already something that is a bit laggy because it's calculated for every vessel regardless of if it's shown or not, better to keep it as lightweight as possible.
