### ISSUE TITLE
[RP-1] Implement variable experiment science caps depending on tech researched

### ISSUE THREAD

**Issue by gotmachine** [Kerbalism/Kerbalism#587]
Feature request for RP-1 : 
RP-1 currently has different "tiers" for some experiments, implemented as separate experiment definitions, unlocked at different tech levels.
If I understand correctly, this is not ideal because it means higher tier experiment parts need to have multiple experiment modules, one for every lower tier.

What we could probably do is have the experiment definition science cap updated when a specific technology is researched.

How to do this :
ExperimentInfo.ScienceCap is a property that doesn't store the value and everything in the codebase is derived from that property, the code for it is : 
`public double ScienceCap => stockDef.scienceCap * HighLogic.CurrentGame.Parameters.Career.ScienceGainMultiplier;`
Theorically, we could add  `* techCap` , where techCap is a [0;1] scalar stored in `ExperimentInfo`
Then, on the tech researched gameevent : 
- we update the scalar according to the config defined value for that tech
- we loop over all existing stock `ScienceSubject` already persisted in the stock RnD DB to update their  `scienceCap` (we maintain a reference to those so that should be easy)

Unless I'm missing something, this *should* work.
Config-wise, that could work with an extra config node inside the `KERBALISM_EXPERIMENT` node, something like :
```
TECH_CAPS
{
  sometech = 0.2
  someothertech = 0.6
  finaltech = 1.0
}
```

**Comment by Standecco** [comment]
This is definitely a step in the right direction, but we would also need a way to limit the science a part (or a module) can obtain, or otherwise it gets a bit messy. Our current setup has different parts for every tier, representing the upgrade in instrument mass or power consumption (and appearance too) over the older tech - in addition to the higher accuracy and thus higher science reward.
We could remove having different parts, but each tier of scientific instrument should definitely have different characteristics - data rate (since more data = higher bandwidth), mass, power consumption, and cost.

Just an example, to clarify:
Imagine you have a old generic thermometer and a fancy new laser one. The new instrument, when "unlocked", allows for more precise measurements, and thus higher science reward. The laser thermometer also has new characteristics, though - it might be lighter or heavier, require more or less current to operate, and will definitely have a different data rate,  given it's more accurate. These differences might make it not worth it to put an incredibly precise instrument, which uses a completely different technology from the previous tiers, but is 3 times as heavy.

If this other request turns out to be too hard or even impossible, we might just make the old tech node update the old parts. Making it mandatory to use the latest unlocked tier.

**Comment by gotmachine** [comment]
Note that this doesn't change the fact that you can have different configs (ec rate, data rate, specific requirements) for separate partmodules on different parts unlocked at different tech levels. This would only change (instantly and game-wide) the "maximum science points" that can be done for a specific experiment definition after a specific technology is researched.

> we would also need a way to limit the science a part (or a module) can obtain

This can maybe be done, not sure. In any case, it would be that **or** the experiment wide tech limits, working with both would make things a huge mess.

But yes, the Experiment module could have a `scienceCapScalar` between 0 and 1 that prevent the experiment from running if `science retrieved in RnD + science collected in flight >= total science value * scienceCapScalar`.

This indeed would be a saner option (from a coding complexity perspective too), but it's problematic in some subtle ways :
- It would prevent the use of the "forced run" feature from any experiment that hasn't got scienceCapScalar = 1.0
- It would make any case of "stuck" collected science in flight (dead vessel, debris...) cause the inability to collect those science points from another vessel (you would have to find and terminate those vessels first). When this currently happen, you always have the possibility of using the forced run feature. A solution could be to provide a way for the player to force the deletion of all in flight data for a given subject (a button in the science archive maybe).

>we might just make the old tech node update the old parts

Note that the stock UPGRADE system will likely not work with the Experiment module. 

In general, for any Kerbalism module, a module field modified by an upgrade won't get the upgraded value on unloaded vessels, unless the field is marked as persistent.

**Comment by nepphhh** [comment]
WRT SirMortimer's KerbalismContracts, the inability to force run on an experiment could be a problem. If you are trying to complete a contract that requires the operation of an experiment, force run is the only way to complete the contract if all data has been collected already.

**Comment by SirMortimer** [comment]
There are several issues we will run into with a game-global cap in experiment definitions. Suppose you have a low-tech and a high-tech temperatureScan, and already have a couple of probes with thermometers orbiting different bodies, experiments are all finished. Then you unlock the higher experiment definition - and suddenly all your probes resume to run the old experiments which now suddenly have additional value. Without the proposed force-run lock, you can even bank on planned upgrades: force-run the experiment for a second run, but wait for the upgrade before transmitting the file. The upgrade will instantly give some scientific values to previously worthless files. This is precisely not what RP1 wants.

Making it mandatory to use the latest unlocked tier isn't a viable solution IMO, because they would also have to remember to disable all experiments _before_ getting the upgrade, also delete all data on all probes and then never enable the experiment again, ever. This is easily forgotten, and many players would end up "cheating" unintentionally.

We could "help" them by disabling old experiments when a new tier is researched, but then you would accidentally kill some of the scientific value of all existing probes that are in transit to new destinations when the upgrade happens (new horizons on a years long journey to Pluto would loose some experiments just because we now have better versions here on earth).

And as @nepphhh pointed out, a force-run lock would prevent most "run experiment X at Y" contracts, especially during early career games when you need them the most.


How about a different approach: we keep multiple experiment definitions, but define a hierarchy of experiment definitions. Maybe something along these lines:

```
EXPERIMENT_DEFINITION {
  id = temperatureScan
  baseValue = 5
}
EXPERIMENT_DEFINITION {
  id = temperatureScan#2
  baseValue = 10
  KERBALISM_EXPERIMENT {
    overrides = temperatureScan
  }
}
EXPERIMENT_DEFINITION {
  id = temperatureScan#3
  baseValue = 20
  KERBALISM_EXPERIMENT {
    overrides = temperatureScan
    overrides = temperatureScan#2
  }
}
```

In code, when we receive a file from temperatureScan#3, we treat it as if it also was a file from all the experiments that it overrides, maybe even credit the science points from the older experiments (that way the first few bytes of data would have higher value than later bytes). When scan no.3 is finished in any situation, even partially (assuming that higher tier experiments produce bigger files) scan no.1 and scan no.2 won't run any more.

**Comment by gotmachine** [comment]
> we keep multiple experiment definitions, but define a hierarchy of experiment definition

Yup this seems like the better option. It's similar in functionality to what I discussed with @Standecco a while ago : having multiple experiment definitions collected at the same time from the experiment module. 
But this feels like a better idea to do it like you say, at the higher level, from the experiment definition. Doing it from the partmodule would have been a huge mess, code wise.

This is still not trivial to implement :
- At DB creation, for each `SubjectData` we register the list of extra SubjectDatas to collect.
- We change `AddScienceToRnDSubject(double scienceValue)` to `AddScienceToRnDSubject(double scienceValue, bool forceCrediting)`.
- When SubjectData.AddScienceToRnDSubject(x.x, false) is called from transmission/recovery, we also call it for every SubjectData in the list, but with `forceCrediting = true`
- When `forceCrediting` is true, we immediately add the science value. We might need to have some buffer like we have for transmission, `ResearchAndDevelopment.Instance.AddScience()` has this issue of killing performance.
- There is an issue with triggering the OnScienceRecieved game event for contracts, currently this is done from the transmission/recovery code because we have some different handling. This might need a bit of refactoring.

**Comment by pap1723** [comment]
This seems like a very useful option!

**Comment by Standecco** [comment]
Aside from the technical aspect of it (upon which I can't comment), @SirMortimer 's solution seems by far the most similar to what we already had, and as such the easiest to implement config wise. I agree that this seems to be the best option here.
