### ISSUE TITLE
Discussion needed re Bureaucracy co-existing with Kerbalisms science system

### ISSUE THREAD

**Issue by severedsolo** [Kerbalism/Kerbalism#588]
I don't think there is a quick fix for this, but thought perhaps we could have a discussion and see if we could work something out.

(Please note I am not a Kerbalism user, I'm basing this on what I've been told by the person who raised the bug, and my own understanding of Science.cs - so please correct me if I'm wrong about something)

**The problem**

Kerbalism uses AddScience to trickle data to the player as experiments are ran, and then fires OnScienceReceived at 95% completion.

This results in science gradually building up in the players store, and then when OnScienceReceived fires, Bureaucracy is taking it away again (Bureaucracy has it's own system for making science take time).

**Sticking Points**
Obviously (I hope) intercepting AddScience through (for instance) OnScienceChanged is not an option, as this would break other mods. I also note that you are using TransactionReasons.None but again, checking for that is not an option as other mods use that for various reasons.

**Potential Solutions**
I've looked through the API and don't see a way to tell that Kerbalism is the one transmitting the science. There is mention [here](https://github.com/Kerbalism/Kerbalism/blob/916dc1e3955932aaf3031b556c570c589813be2e/src/Kerbalism/Science/Science.cs#L279) of an event that was disabled due to performance concerns, perhaps it could be turned back on again each time Kerbalism transmits? (Again, performance concerns, so totally understand if that's not an option)

The other option of course would be to direct users to disable Kerbalism's science system, or Bureaucracy's but I feel the two synergise well and it would be a shame if we can't get them working together.

Otherwise I'm happy for suggestions / something in the API that I may have missed.

**Comment by SirMortimer** [comment]
What would be the ideal solution? As far as I understand you want to be "in between" science results and the R&D facility, so instead of crediting science to R&D you do something else first, ideally just sum up accumulated science in your mod iso. of booking it directly to R&D.

Don't know if it is possible (@gotmachine might able to say that) - how about

1. depending on a config option, we trigger the event at 99.9% instead of 95%
2. depending on a config option, we don't call `ResearchAndDevelopment.Instance.AddScience` but trust that it will be called somewhere else

Would something along that be a better solution?

**Comment by severedsolo** [comment]
That seems like the ideal solution to me. So my understanding is that you would fire OnScienceReceived but let Bureaucracy deal with actually giving the player the science.

I'd have to deal with not taking the science away at my end if Kerbalism is triggering it, but detecting another if another mod is installed is easy enough to do.

How does Kerbalism deal with it's configs? Is it something that I could patch (say via ModuleManager) or hook into via the API? - I'm aware that Kerbalism is very configurable, and would want to make sure the player actually had Kerbalism's Science system turned on.

**Comment by gotmachine** [comment]
Yup, tried Bureaucracy recently, I knew this was coming ;)

We can't fire `OnScienceRecieved `continuously on every bit of science transmitted because that break contracts, and cause issues with other mods like Strategia or Chatterer, as well as being a performance issue.

As @SirMortimer suggested, it would be a simple solution (when bureaucracy is present) to disable our continuous calls to `ResearchAndDevelopment.Instance.AddScience` and call it only once, just before we call `OnScienceRecieved `.
Note that we don't fire at 95% completed, but when there is less than 0.01 science point left to collect, so that's a non issue.

But I don't think that will work from a gameplay standpoint. The kerbalism science progression is balanced around the fact that you will get science continuously, but experiment completion can take a lot of time and effort, you often won't get it with a single launch/mission, and some experiments can take months/years to complete. With that proposed solution, I'm pretty sure it would be unplayable.

I think the right way to do this is for us to implement a reflection callable API with :
- A static bool, that you set to true : disable continuous AddScience calls and change all our firing of OnScienceRecieved to pass 0 science points.
- An API event that you subscribe to, that is triggered at regular intervals (every 5 days feels good enough), that pass a list of subjects and the science value for each of them. When you receive that event, you don't remove the science value (since it will not have been credited) but do register the subjects as usual, like you would have done with OnScienceRecieved.

**Comment by severedsolo** [comment]
That works for me, Bureaucracy already ignores On Science Received if its being passed <0.1 science anyway, and registering for an event would mean minimal changes my side (On Science Received just calls another method in the Research Manager, I just get the Kerbalism event to do the same thing)

**Comment by gotmachine** [comment]
Okay, I will try to look into it at the same time of the new science system features for RP1.
Will keep you informed.

**Comment by gotmachine** [comment]
@severedsolo See https://github.com/Kerbalism/Kerbalism/blob/d95426925e9152ffb7bd58db4c7d89891e27cf4b/src/Kerbalism/System/API.cs#L509

**Comment by severedsolo** [comment]
Cool, if you want to pass me a build when you are ready for it to be tested, I'll give it a whirl (I have no idea how to build Kerbalism, I've tried before)

**Comment by gotmachine** [comment]
Just gave a look at your code, a couple of remarks on this bit : 
```
        public void NewScienceReceived(float science, ScienceSubject subject)
        {
            Debug.Log("[Bureaucracy]: New Science Received "+subject.title+" for "+science+" science");
            if (science < 0.1f)
            {
                Debug.Log("[Bureaucracy]: "+subject.title+" worth less than 0.1 science. Skipping");
                return;
            }
            ProcessingScience.Add(new ScienceEvent(science, subject, this));
            Debug.Log("[Bureaucracy]: Registered new science event "+subject.title+" for "+science+" science");
        }
```

- It's quite likely that Kerbalism will return values < 0.1, especially on long term experiments. Not sure why you added that but that will certainly cause some science to be lost.
- You will receive many times the same subjects, not sure how much an issue it is and feasible it is, but you should probably change ProcessingScience to a dictionary<string, ScienceEvent> where the string is `ScienceSubject.id`, then add the `science` param value to the existing `ScienceEvent`. Otherwise you will probably have hundreds of ScienceEvent being processed. Alternatively, you can change the intervals at which you get the event in the trough the API. By default it's every minute of real time, or every 5 days of game time, whatever is reached first.
- Not sure how you do the value processing, but if you do some math operation on the science value every update, I suggest you move everything from float to double.

**Comment by severedsolo** [comment]
The <0.1f was for handling the stock system - "recovery of a vessel" was passing ridiculously small amounts, so I needed a way to filter them but I should probably make the threshold a couple of powers of ten smaller (or write a new method for Kerbalism - at the moment it's just hooking into the one that was already there).

I had considered the "multiple events" thing - it's already kind of a problem in stock, but you are right Kerbalism is going to make that problem alot worse - will take that suggestion :stuck_out_tongue: 

Yeah I should probably make those double's I think I just used floats as that's what stock gave me.

This is literally first draft on the Kerbalism branch :stuck_out_tongue: - I was more concerned with actually getting the reflection working tonight (but thank you for the feedback, it is helpful)
