### ISSUE TITLE
DeepFreeze is incompatible

### ISSUE THREAD

**Issue by gotmachine** [Kerbalism/Kerbalism#620]
Apparently recent version of DeepFreeze just don't work anymore without BackgroundResources

**Comment by TBleader** [comment]
I think I have encountered this. Occasionally my game crashes, I cannot confirm it is because of this, but I can confirm something is funky with deepfreeze as it is generating a lot of errors.

`File name: 'BackgroundResources, Version=1.8.0.0, Culture=neutral, PublicKeyToken=null'
  at DF.DFIntMemory.FixedUpdate () [0x000e4] in <7af91bed077f41e084c7046065caa85e>:0 
[LOG 00:20:44.133] 4/17/2020 12:20:44 AM,DeepFreeze,FixedUpdate failed to update DeepFreeze Internal Vessel Memory
[LOG 00:20:44.133] 4/17/2020 12:20:44 AM,DeepFreeze,Err: System.IO.FileNotFoundException: Could not load file or assembly 'BackgroundResources, Version=1.8.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'BackgroundResources, Version=1.8.0.0, Culture=neutral, PublicKeyToken=null'
  at DF.DFIntMemory.FixedUpdate () [0x000e4] in <7af91bed077f41e084c7046065caa85e>:0 
[LOG 00:20:44.156] 4/17/2020 12:20:44 AM,DeepFreeze,FixedUpdate failed to update DeepFreeze Internal Vessel Memory
[LOG 00:20:44.156] 4/17/2020 12:20:44 AM,DeepFreeze,Err: System.IO.FileNotFoundException: Could not load file or assembly 'BackgroundResources, Version=1.8.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'BackgroundResources, Version=1.8.0.0, Culture=neutral, PublicKeyToken=null'
  at DF.DFIntMemory.FixedUpdate () [0x000e4] in <7af91bed077f41e084c7046065caa85e>:0 
[LOG 00:20:44.158] 4/17/2020 12:20:44 AM,DeepFreeze,FixedUpdate failed to update DeepFreeze Internal Vessel Memory
[LOG 00:20:44.158] 4/17/2020 12:20:44 AM,DeepFreeze,Err: System.IO.FileNotFoundException: Could not load file or assembly 'BackgroundResources, Version=1.8.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.`

I have deleted BackgroundResources as instructed in the FAQ/Mod Compat list. 
I uploaded my entire KSP log in case it helps.
KSP 1.8.1 (not all of the mods I want to use are on 1.9.x)
OS: Linux
Modlist:

> 
			"name": "DMagicOrbitalScience"
			"name": "KAS"
			"name": "KerbalAlarmClock"
			"name": "KerbalAtomics"
			"name": "KerbalEngineerRedux"
			"name": "Kerbalism"
			"name": "KIS"
			"name": "SCANsat"
			"name": "StationPartsExpansionRedux"
			"name": "surfacelights"
			"name": "CommunityTechTree"
			"name": "StageRecovery"
			"name": "ContractConfigurator"
			"name": "NearFutureConstruction"
			"name": "NearFutureSolar"
			"name": "NearFutureSpacecraft"
			"name": "CryoTanks"
			"name": "Kerbalism-Config-Default"
			"name": "CommunityCategoryKit"
			"name": "FinalFrontier"
			"name": "B9PartSwitch"
			"name": "CommunityResourcePack"
			"name": "DeployableEngines"
			"name": "ClickThroughBlocker"
			"name": "ZeroMiniAVC"
			"name": "ToolbarController"
			"name": "NearFutureProps"
			"name": "NearFutureSolar-Core"
			"name": "CryoTanks-Core"
			"name": "DynamicBatteryStorage"
			"name": "AstronomersVisualPack"
			"name": "Chatterer"
			"name": "ContractConfigurator-CommNetRelays"
			"name": "DistantObject"
			"name": "PlanetShine"
			"name": "Scatterer"
			"name": "TexturesUnlimited"
			"name": "VenStockRevamp"
			"name": "TextureReplacer"
			"name": "VenStockRevamp-NewParts"
			"name": "AVP-8kTextures"
			"name": "Scatterer-sunflare"
			"name": "EnvironmentalVisualEnhancements"
			"name": "DistantObject-default"
			"name": "PlanetShine-Config-Default"
			"name": "Scatterer-config"
			"name": "VenStockRevamp-Core"
			"name": "KerbalPlanetaryBaseSystems"
			"name": "MechJeb2"
			"name": "ExtraPlanetaryLaunchpads"
			"name": "KerbalStats"
			"name": "Toolbar"
			"name": "ContractConfigurator-CleverSats"
			"name": "ContractConfigurator-ExplorationPlus"
			"name": "ContractConfigurator-KerbinSpaceStation"
			"name": "AlternateResourcePanel"
			"name": "TriggerAu-Flags"
			"name": "Olympic1ARPIcons"
			"name": "NearFutureExploration"
			"name": "SXTContinued"
			"name": "FirespitterCore"
			"name": "FirespitterResourcesConfig"
			"name": "RetractableLiftingSurface"

[KSP.log](https://github.com/Kerbalism/Kerbalism/files/4491568/KSP.log)

For now I think I'll just get rid of deepfreeze. As much as I love the idea of freezing my kerbals to save on resources, I'd rather play with the fun Kerbalism stuff. Guess I'll be building big once it comes time to go to Duna.

**Comment by Tonas1997** [comment]
I'm also getting those console errors; however, I haven't noticed any performance hits or instability that can be traced to this issue.

**Comment by gotmachine** [comment]
So, a quick investigation, I confirm that DeepFreeze now has a hard(er) dependency on BackgroundResources that cause it to not work as intended.
More problematic, it will spam the log with errors, which is a noticeable performance issue, and can eventually eat gigabytes of disk space on long play sessions.
There isn't much we can do on our side, up to JPLRepo to make the BackgroundResource dependency optional when Kerbalism is installed.

**Comment by JPLRepo** [comment]
I don't see the issue. You've advised users of your mod to remove part of my mod?
Without consultation. Yes it has a hard dependency. If the user wants to run DeepFreeze they should not be removing dll files that are included in the install.
If this DLL is causing issues for your mod regarding compatibility then I suggest that the user could disable the backgroundresources processing in the difficulty settings for their game. and it won't do anything...... problem solved.

**Comment by gotmachine** [comment]
> You've advised users of your mod to remove part of my mod?

Well, it used to be a viable solution for quite some time, but to be honest we never payed much attention as nobody among the Kerbalism contributors play with DF and we weren't asked much about it. 

Now, looking at how BR and DF interact, it indeed looks like that the BR behaviour is to only be activated for a vessel if another mod explicitly request that vessel to be simulated, and the difficulty settings option indeed seems to provide that.

But I don't consider that a viable option to request users to remember to untick (or to know that they shouldn't tick) that box for every new game, that will be overlooked in almost all cases, especially since the consequences of having the two competing background simulations running at the same time aren't immediately obvious. 

Now it seems that in the latest version that option is defaulting to disabled, but I'm pretty sure I've seen it defaulting to enabled when I checked previously. 

We could force it trough reflection, but that's not really a solution to the whole issue. 
We don't know what other mods might be using/activating BR in our back (beside DF, is there only TAC-LS ?), that's why having it installed is an issue in itself and why it is marked as incompatible on CKAN and from our compatibility checker.

I understand that you want to have BR as a hard dependency for DF, easier to manage things that way. Maybe you could consider exposing some sort of "master kill switch" in BR, that we can set from our side and that is handled gracefully by DF (and potentially other plugins using BR, when the BR dependency can be made optional). 

I've seen the difficulty settings switches of BR, but it seems to me that they aren't fully implemented, I fail to see how the code make use of them to properly disable the actual processing.

**Comment by gotmachine** [comment]
Ok, looks like disabling the difficulty option works well enough, also implemented it for TAC-LS since a similar option is provided.
BackgroundRessources seems to be only used by those two mods, I guess we can un-blacklist it and hope that those measures will be enough for it not not enable itself.
![image](https://user-images.githubusercontent.com/24925209/81955597-93b25a00-960a-11ea-911f-57c96e54e96e.png)

**Comment by zaafonin** [comment]
The
https://github.com/Kerbalism/Kerbalism/wiki/Home-~-Mod-Support
page marks DeepFreeze as incompatible, while
https://kerbalism.readthedocs.io/en/latest/support.html
says it's ok. This issue suggests it's compatible-ish. So what's the compatibility status?
