### ISSUE TITLE
Suggestion: signal delay

### ISSUE THREAD

**Issue by Tonas1997** [Kerbalism/Kerbalism#636]
First of all, I'm not exactly sure whether or not this has been discussed before, but an optional setting for delayed vessel commands could be a nice addition to Kerbalism.

Argumentation:

- Signal delay is a fundamental part of unmanned spaceflight. Even without considering how this limitation would have to be bypassed with kOS-like scripts - which, admittedly, is not up everyone's alley, hence the option to enable/disable it - delayed communications will also have an outstanding influence on how long-term, crewed interplanetary voyages are going to be conducted in the future. Integrating such a mechanic with Kerbalism's "call home" factor could present an interesting challenge, possibly lowering its effectivness as real-time interactions become impossible at longer distances.

- Most current and past attempts at signal delay are either not very fleshed-out or are linked to more substantial comms overhauls such as RemoteTech: the latter presents an interesting case, as the move from this mod to RealAntennas has left the RSS/RO player base without a solid signal delay mechanic.

Now, I don't have that good of a grasp on how signal delay is implemented. What I _do_ know, however, is that it's not that trivial to implement, specially when we're talking about capturing and caching behavious across multiple custom part modules. So this is more of a brainstorming prompt, if you will 😄

**Comment by gotmachine** [comment]
>  however, is that it's not that trivial to implement

> Most current and past attempts at signal delay are either not very fleshed-out or are linked to more substantial comms overhauls such as RemoteTech

> this is more of a brainstorming prompt, if you will 

I think you pretty much answered the whole discussion by yourself. Signal delay is a lot of work, by itself, and also on the quite problematic mod inter-compatibility front, as every plugin that has an UI that control something on the vessel has to implement it. That's why only the venerable RemoteTech has a more or less satisfying level of integration with everything else, and why the SignalDelay plugin has a hard time providing a decent experience.

To that, I will add that without a good mean of automating everything, signal delay is just a bad idea gameplay-wise. Without a kOS+MechJeb level of automation, that's just imposing arbitrary restrictions.

So in the end, my stance on this is that this doesn't justify a the huge amount of work of writing a plugin for it, as in the end there are two ways of playing : 
1. You want realism in how an unmanned spacecraft is controlled ? Then just do everything trough kOS or mechjeb, signal delay or not.
2. You consider that you, the player, is the computer and you can control things directly.

Now in the context of Kerbalism, providing UI compatibility for a signal delay mod is probably never gonna happen given the amount of work that would require. 
As for gameplay mechanisms like the call home factor... well, why not, but frankly that's quite minor.

What's sure is that implementing signal delay is 100% out of scope for Kerbalism. We rely on external code for providing a comm network, either CommNet, RA or RemoteTech, its' unlikely we will ever implement an in-house replacement.

**Comment by Tutul-** [comment]
You can have signal delay with RemoteTech, the support for it is still working and it seem that a full support is going to be available again (as you said yourself). You can configure RemoteTech to be as close to stock as possible with the SignalDelay (and it work with some other mods too like KOS).

**Comment by SirMortimer** [comment]
This won't be implemented in Kerbalism.
