### ISSUE TITLE
How to protect important processes from energy-hungry processes?

### ISSUE THREAD

**Issue by basilicofresco** [Kerbalism/Kerbalism#643]
@gotmachine in https://github.com/Kerbalism/Kerbalism/issues/638#issuecomment-633297900 said:
*EC level / sunlight state automation events don't work reliably at medium/high timewarp speeds.*
[...]
*Since that issue keep popping, and because we have no way to make those automation triggers work reliably, we have decided that they will be removed in the future.
We are also revisiting how things works regarding EC management to make those "underpower" situations a bit less annoying, in particular by allowing you to keep control when the vessel doesn't have any EC left but is still producing enough for "basic needs" like comms and command (or avionics in RO)*

Personally I could live without a fast warp speed. However I wonder if there will be a simple way to protect important processes from energy-hungry processes without low battery triggers.
Eg. Protecting life support / comm or H2 liquefaction from a huge electrolysis rig.

Could it be possible with a battery flagged as "emergency reserve" that can be used only by processes flagged as "critical"?
Maybe to flag an energy-hungry process as "non critical" in order to avoid to use batteries, just generators?
Maybe with the possibility to disable EC crossfeed on selected docking ports in order to separate living quarters from chemical plants?
Maybe limiting the warp speed when there are somewhere these triggers activated?
Thanks!

**Comment by gotmachine** [comment]
> Could it be possible with a battery flagged as "emergency reserve" that can be used only by processes flagged as "critical"?
Maybe to flag an energy-hungry process as "non critical" in order to avoid to use batteries, just generators?
Maybe with the possibility to disable EC crossfeed on selected docking ports in order to separate living quarters from chemical plants?

I have some future plans that would allow the player to freely divide a vessel into isolated "sections" that would be independent from one another resource wise, with the ability to toggle separately in and out crossfeed between each section, for each resource, 
But it's a big feature, and not on the table currently.

> Maybe limiting the warp speed when there are somewhere these triggers activated

That's definitely not an option. And even if it was, those triggers are conceptually a bad idea, they just don't work. 

As said in the other issue, we are changing quite a lot of things regarding how resources and processes work. I'm confident that those changes will result in a much less wonky and frustrating overall behavior, especially in regard to randomly dying kerbals.

**Comment by basilicofresco** [comment]
Ok, thanks.
