### ISSUE TITLE
Breaking Ground Small Scanning Arm 100% Science Return

### ISSUE THREAD

**Issue by Odieman1** [Kerbalism/Kerbalism#722]
### **Info:**

 Scanning Arms of various sizes offer various science outcomes.  In Kerbal fashion, the bigger the better.  Small arms offer 33%  science returns, medium 66%, and large 100%.  If a surface feature would give you 100 science from the large scanning arm, it would give you 33 science from the small scanning arm.  You can choose to keep the data or transmit it which does not change the amount of science returned.  I'm assuming this is purposeful, as scanning arms are generally attached to a probe or rover.

### **Expected Behaviour:**

Rovers should receive handicapped science returns if they are equipped with a less-than-large scanning arm.  Also, being Kerbalism, a portion of the data would be transmissible quickly and the other portion would need to be analyzed over time much like rovers do in reality.  Alternatively, some form of recovery mission could retrieve the physical data and bring it back to Kerbin.

### **Actual Behavior:**

No matter what scanning arm you use, you receive the full science bonus.  For large scanning arms, there is a drilling animation that implies a sample has been taken.  The UI that appears is not related to Kerbalism but rather 'classic' Kerbal Space Program UI.  No sample mass is added to the rover.

### **Potential Behaviours:**

Higher 'levels' of Scanning Arm could be faster, return more science, gather physical data, allow for greater transmissible data, or potentially allow for a standard surface sample from rovers, a feature that is currently missing.

**Game Info:**

**Version of Kerbalism: 3.12
KSP Version: 1.11.1**

**Mods:**
![image](https://user-images.githubusercontent.com/42369900/111098459-e81fb200-8519-11eb-98ad-f20dd31839f1.png)

_Output Log isn't necessary as this isn't an inherent issue but rather a missing feature._

**Comment by gotmachine** [comment]
This has been discussed extensively, and we have no solution for this.
As you noticed, the rover arms experiments (ROCs) are entirely done through the stock code/system, we only convert the collected data into Kerbalism's files. 

I won't go into the details, but the issue is that Kerbalism science system is fundamentally incompatible with the stock feature that say "a result for experiment X on part Y only yield Z% of the science points for that experiment", mainly due to the "science over time" Kerbalism feature. Said otherwise, even if we had that feature, there is nothing that would prevent you to run the small arm (33% return) 3 times to get the full science value.

We have ways to do something conceptually similiar to that stock feature (tiered experiments), but the ROCs experiments have a very special handling in the stock system that make this difficult to do. And that would require to duplicate every ROC definition for each rover arm size, which would be quite a mess and cause side issues with contracts.

The consensus on that issue is that it is relatively minor, while fixing it would require a lot of work. Moreover, Kerbalism always had that policy to avoid grindy science features that require you to go repeatedly to the same place to get the full science rewards.

**Comment by Odieman1** [comment]
Understandable.  I'd be lying if I said I didn't keep the science returns from Eve's small-handed rover.  The effort to get that rover there with an entire minute of signal delay and no reloads or reverts felt worth it 😛.

It feels counter to tradition that these ROC's are not modular or allow code manipulation but I can only assume this is to prevent a mod that emulates the DLC.  Anyway, since I have the ability to close this I will and allow you to work on things more important.  Thanks for the response and thank you for maintaining this mod for weird masochists like me.
