### ISSUE TITLE
Can't run crew experiments while in Science mode

### ISSUE THREAD

**Issue by JustinHuPrime** [Kerbalism/Kerbalism#726]
I'm playing a science mode game, but it looks like I can't run any crew experiments - documentation about crew experiments seems a little light as well.

I built a craft to run the FLIGHT crew experiment, and I have researched the pre-req technology. It doesn't look like there's any options to add the experiment to my craft, nor can I run it when I am in the required situation (in space low over Kerbin).

What other information would be helpful to chase down this issue?

**Comment by UsernamesAreAlwaysTaken** [comment]
Just to keep you in the loop:

File:
Kerbalism/GameData/KerbalismConfig/System/ScienceRework/Patches-Early-Parts.cfg 

Line:
'
@PART[*]:HAS[#CrewCapacity[>3],!MODULE[ModuleCommand],!MODULE[Laboratory],!MODULE[StationScienceModule],!MODULE[LaunchClamp]]:NEEDS[FeatureScience]:FIRST'

This is the line that filters parts to assign crew experiments to.

If you're not familiar with MM syntax, it basically looks for parts that have more than 3 crew, are not command pods/drone cores and not a laboratory (the others are weird interacrions with other mods).

This was an intentional design decision, so you have a reason to hurl heavy habitat parts across the kerbol system besides keeping your little green astronauts alive.

Feel free to remove some restrictions as you please for your playthrough.

And i agree, it needs documenting.

**Comment by Mathematician23** [comment]
@UsernamesAreAlwaysTaken Just wanted to say thanks even though this is several months old. I had the same problem and this fixed it lol
