### ISSUE TITLE
Engine reliablity not functioning on KSP 1.11.2

### ISSUE THREAD

**Issue by BTAxis** [Kerbalism/Kerbalism#741]
As per title. Engines have no reliability rating, have no quality toggle and do not fail.

I've tested this with just the required dependencies for Kerbalism 3.13 and nothing else. I've also tested on KSP 1.10.1 using the exact same mods (copied them over from the 1.11.2 install). In this instance it works as expected.

Based on this, it would appear that someting in KSP 1.11.2 is stopping the engine reliability from working.

**Comment by gotmachine** [comment]
Must be an installation issue on your side, there a lot of people using reliability on KSP 1.11.2...
Maybe something due to some unwanted mod interactions ?
Please provide further info (upload your KSP.log or make a bug report with [KSPBugReport](https://github.com/KSPModdingLibs/KSPBugReport)) otherwise there isn't much we can do to help.

**Comment by BTAxis** [comment]
Seems like you're right about some mod interaction, because I deleted my Module Manager cache, and now reliability is showing up again. I don't know what was going on there, but clearly this report can be safely disregarded.
