### ISSUE TITLE
Perhaps give ModuleDeployableSolarPanel with panelType SPHERICAL more than 25% exposure?

### ISSUE THREAD

**Issue by Gordon-Dry** [Kerbalism/Kerbalism#773]
https://github.com/Kerbalism/Kerbalism/blob/1d6c68e090d9f07092306f2e0702aec4a5908e1f/src/Kerbalism/Modules/SolarPanelFixer.cs#L911

Is this even mathematically correct, that if a spherical solar panel that gets light from one nearby star has a max exposure of 25% ?
How about 33% ?
I'm not a mathematician, but 25% seems low.

**Comment by Gordon-Dry** [comment]
The planner in VAB could help out by using the max. exposure so there is no bad surprise as soon as the spherical probe coated with solar panels is in orbit.

**Comment by gotmachine** [comment]
The 0.25 factor is from the stock module. 
It "mathematically" doesn't make any sense, since a spherical panel, by definition, isn't affected by the sun angle.
Since we are just a "wrapper" around the stock module logic, we have to follow that convention, no matter how silly it is.

**Comment by Gordon-Dry** [comment]
I helped me out for now with this hacky patch in my zFinal folder:
GameData\zFinal\zzz_Kerbalism_Kopernicus_panelType_SPHERICAL_fix.cfg
```
@PART[*]:HAS[@MODULE[ModuleDeployableSolarPanel]:HAS[#panelType[SPHERICAL]]]:NEEDS[Kopernicus,KerbalismDefault]:FINAL
{
    @MODULE[ModuleDeployableSolarPanel]:HAS[#panelType[SPHERICAL]]
    {
        @panelType = CYLINDRICAL
    }
}
```
By pointing the probe SUN-DOWN I achieve 32% exposure now. But still worse than what the planner in VAB predicted.

**Comment by gotmachine** [comment]
I'm not sure what you are trying to fix.

A panel part defined with `panelType = SPHERICAL` is supposed to have a `chargeRate` defined according to the 25% exposure rule. Said otherwise, for a spherical panel, `effective charge rate` = `chargeRate` * 0.25
If the part author didn't take that into account, that's not our problem.

As for the "nominal exposure" planner prediction, indeed, it should be applied that 25% factor and it doesn't.
