### ISSUE TITLE
Kerbalism and Near Future bug

### ISSUE THREAD

**Issue by Assan75** [Kerbalism/Kerbalism#777]
I have Herbalism mods and a Near Future mod pack. If there is a crew on the ship, then the ship is deformed more and more to a terrifying appearance with each qicksave - qickload cycle. I wrote a script on KOs to track the deformation of the direction of the parts relative to the root. The deformation begins to gradually appear even on the launch pad after several save/load cycles, although the ship has never even turned on the engines.
![29a31511-4f58-4a92-bc85-89181fc55db2](https://user-images.githubusercontent.com/94815001/142794238-432e3680-f035-4d72-a318-d61420cf4893.jpg)

**Comment by gotmachine** [comment]
Which KSP version ?
Try installing https://github.com/KSPModdingLibs/KSPCommunityFixes

**Comment by Assan75** [comment]
My KSP version is 1.12.2.3167(x64). MK 1.12.1. BG 1.7.1.
"max physics delta time" changed to 0.03. KSPCommunityFixes mod installed. The bug remained.

![screenshot0](https://user-images.githubusercontent.com/94815001/142847681-813859f0-39bd-4029-b6b4-3a9373bc2c2a.png)
![screenshot1](https://user-images.githubusercontent.com/94815001/142847686-da17f8b1-99d5-450e-8bbe-4ecf4a6f2ccd.png)

My script prints parts in the console that are shifted relative to the root by an angle greater than 0.1. However, the same parts in the sfs file with an angle of 0.

For example:

part
{
name = sspx-inflatable-hab-125-1
cid code = 4290085332
liquid ID = 173868140
average = 656082751
permanent id = 3006028549
started = 124
parent = 52
position = 0,13.003902435302734,0
rotation = 0,0,0,1
mirror = 1,1,1

In the process of searching for the cause of the bug, I noticed that it is somehow related to autostrutMode. If you disable autostrutMode for all parts, save and load the game, the ship will not deform. But if the ship consists of a large number of parts, then constantly switching strut modes is very tedious. I wanted to write a script on KOs to switch strut modes automatically before saving, but I couldn't find this field in the parts:modules structure :-(

**Comment by gotmachine** [comment]
I suggest to run the game again and to try to reproduce the issue with a brand new vessel. There are many ways an existing saved vessel can be borked. Once you have reproduced the issue, upload your KSP.log, there isn't much I can do to help without that (or better, use https://github.com/KSPModdingLibs/KSPBugReport)

That bug is indeed tangentially related to autostruts. More specifically, it's caused by the part components initialization order being borked under certain conditions, causing autostruts to be applied before the actual part joints are created, causing parts to be "pulled away" by the elasticity of the autostrut joints for a few frames. KSPCommunityFixes should be preventing that, in theory. It's strange that it doesn't work for you, so I suspect something else is at play, possibly another mod or an exception/error in the loading process.

As for why you can find autostruts in any module fields, it's because they are managed at the part level. I'm not sure if kOS can access that.

**Comment by Assan75** [comment]
I created a completely new ship, similar to the previous one (and saved a lot of delta :-)). I attach a bug report from the mod. I noticed interesting features of the bug. For example, if you load a save without a bug, then with bug, and then again the first save, then the ship also becomes deformed. It's as if the ship in the "clean" save is "infected" from the ship in the second save. It looks like the information about the ship or its parts is stored somewhere else besides the save file (possibly somewhere in the Kerbalism files).
I also noticed that the bug is missing in unmanned ships. Also, if the whole crew goes into space, make a quicksave, and then quickload, then the deformation of the ship disappears!
[KSPBugReport_2021-11-23_223931.zip](https://github.com/Kerbalism/Kerbalism/files/7590039/KSPBugReport_2021-11-23_223931.zip)
s!

**Comment by gotmachine** [comment]
Ok, turns out there was in issue in KSPCommunityFixes, causing the patch to not work. 
Could you try again with the latest release (1.5) ?

**Comment by Assan75** [comment]
Thank you so much, I finally solved the problem with this damn bag. On your advice, I changed the maximum physics to 0.01 in the KSP config file, since the interface allows you to set only 0.03 minimum. I named my first mun station after you :-).
