### ISSUE TITLE
High/Low space situation automation

### ISSUE THREAD

**Issue by JonSeverinsson** [Kerbalism/Kerbalism#813]
The Kerbalism automation system has scripts when entering atmosphere or space, but not when moving from space high to space low or vice versa. That functionality would be very useful for science orbiters that spend most of their orbit in space high collecting data, but dips down into space low at perigee in order to transmit that data at a reasonably fast rate.

**Comment by gotmachine** [comment]
Why not just keep transmitting all the time ?

The problem with such automation events is that they fundamentally don't really work anymore at mid/high timewarp speeds, because the simulation time-step can becomes greater than the new state duration. See also https://github.com/Kerbalism/Kerbalism/issues/638

**Comment by JonSeverinsson** [comment]
> Why not just keep transmitting all the time ?

Because then it uses 8 times the electricity to send the same amount of science, at which point my craft runs out of power...

> The problem with such automation events is that they fundamentally don't really work anymore at mid/high timewarp speeds, because the simulation time-step can becomes greater than the new state duration.

Is there some reason you can't calculate what portion of the time-step was in each state and calculate averages separately for each, before adding them together? I thought solar panels already worked that way for in shadow/sunlight...

**Comment by gotmachine** [comment]
> Because then it uses 8 times the electricity to send the same amount of science, at which point my craft runs out of power...

The solution to that is a better power management system. I'm fully aware of those issues, but automation is not the right tool. What we need is a way to define priorities for EC consumers and producers.

> Is there some reason you can't calculate what portion of the time-step was in each state and calculate averages separately for each, before adding them together?

Because it essentially comes down to running the whole simulation at a lower time step, which is difficult to implement and has massive performance implications. The solar panel "analytic mode average" is a band-aid workaround having many shortcomings, and it's not a solution that can be generalized.

For example, in your specific use case, transmission speed and EC cost is a result of the CommNet implementation, which is out of our control. So even if we somehow had those "averages", the end result would still be using the comms state of the large timestep and the event would be essentially useless.
 
In the end, we just have to accept that the ability to timewarp (fast) comes with an inherent reduction of the simulation precision. From there, aside from limiting timewarp speed (which isn't a viable option IMO), the way Kerbalism can handle that is by implementing mitigation measures when possible, but mainly by being careful to not implement features too sensitive to that issue. 

Judging from years of user feedback, the whole automation thing is a bad idea. People spend time trying to use it because it sounds like a solution to their mission design requirement, and then just get frustrated because they don't work as expected. Past a point, a broken feature is worse than no feature.
