### ISSUE TITLE
[request] Make TVs and RDUs optional

### ISSUE THREAD

**Issue by rocket-girl-e** [Kerbalism/Kerbalism#851]
I've just unlocked Advanced Science Tech in my Kerbalism career play through and noticed cost of all habitat units rising up to ridiculous levels. I've looked around and found that RDUs increase it by 275300 funds and are irremovable. TVs also are irremovable and cost 33500 funds (missed that cost increase earlier because it wasn't that big). This makes space stations prohibitively expensive (especially those 100m^3 space stations required for some experiments - even with some command modules and labs it still requires about 10 Hitchhiker modules - with TVs and RDUs it's about 3M funds) for a feature that isn't even really needed in LKO (especially since it's easy to just haul a lot of shielding there). For interplanetary travel - one RDU for a craft is probably enough and 275300 is completely reasonable price for it, but forcing this module into every single one of many habs that will be on the ship increases cost by millions.

**Comment by hovigk5** [comment]
**Found and tested lots of strange behavior regarding sickbays. I've included a fix for the ridiculous costs at the end of this comment for anyone interested:**
![image](https://user-images.githubusercontent.com/44655570/224073344-56e870d7-e384-45ab-a974-3a5d4f567646.png)

1. Hovering over a part that has a sickbay will cause ALL editor parts to display the normal part cost, + upgrade cost of TV or RDU, whichever you purchase first. This bug does not actually increase non-sickbay part costs. This also applies to Station Parts Redux mod parts that have sickbays. I am running career hard mode. 

Turning off part upgrades in advanced settings will fix this behavior but does not remove the extra costs associated with sickbay upgrades. Leaving and reentering editor will fix this until you hover over a sickbay.

2. Sometimes sickbays will received upgrades without having the nodes and upgrades unlocked. In this case the upgrade costs are not attached to the sickbays at all. They seem to draw power and function normally. This may be recreated by loading saves that have already unlocked sickbay upgrades.


In order to lower the prices you can edit Sickbay.cfg in GameData/KerbalismConfig/System
Open the file using notepad and adjust the cost of the RDU and TV, then save the file. Would not recommend setting the costs to 0 as this may cause issues. It is also possible to edit the default.cfg in /KerblismConfig/Profiles to increase healing rates for radiation and comfort.

**Comment by Tahvohck** [comment]
Here's a Module Manager patch that removes the automatic upgrade status of the sickbay items and turns them into configurable items just like the experiments and life support:

```
@PARTUPGRADE[Upgrade-*RDU|Upgrade-TV]:HAS[#cost,!entryCost]:NEEDS[Kerbalism]:FINAL
{
	%entryCost = #$cost$
	-cost = 0
}

@PART[*]:HAS[@MODULE[Sickbay]]:NEEDS[Kerbalism]:FINAL
{
	MODULE
	{
		name = Configure
		title = Sickbay Modules
		slots = 1
		SETUP
		{
			name = None
			desc = Empty slot for mass and cost savings.
		}
		SETUP
		{
			name = Tranquilizing Vortex
			cost = #$@PARTUPGRADE[Upgrade-TV]/entryCost$
			@cost /= 10
			mass = 0.1
			tech = #$@PARTUPGRADE[Upgrade-TV]/techRequired$
			desc = A tranquilizing vortex (TV) uses low quality distraction to put the crew into a state of apathy. It also relieves some of the stress, effects on dumbness are said to be hearsay.
			MODULE
			{
				type = Sickbay
				id_field = resource
				id_value = _SickbayTV
			}
		}
		SETUP
		{
			name = Radiation Detoxication Unit
			tech = #$@PARTUPGRADE[Upgrade-HitchhikerRDU]/techRequired$
			cost = #$@PARTUPGRADE[Upgrade-HitchhikerRDU]/entryCost$
			@cost /= 10
			mass = .75
			desc = The Radiation Detoxication Unit (RDU) uses <b>EC</b> and <b>Oxygen</b> to reduce the effects of radiation poisoning.
			MODULE
			{
				type = Sickbay
				id_field = resource
				id_value = _SickbayRDU
			}
		}
	}
	
	@MODULE[Sickbay]:HAS[#resource[_SickbayTV]]
	{
		%slots = #$UPGRADES/UPGRADE/slots$
		%cureEverybody = #$UPGRADES/UPGRADE/cureEverybody$
		sickbay_id = kerbalism_TV
		-UPGRADES {}
	}
	
	@MODULE[Sickbay]:HAS[#resource[_SickbayRDU]]
	{
		%slots = #$UPGRADES/UPGRADE/slots$
		sickbay_id = kerbalism_RDU
		-UPGRADES {}
	}
}
```

**Comment by gotmachine** [comment]
Should be fixed by above commit which make RDU/TV configurable in the same spirit as the patch proposed by @Tahvohck 

> Sometimes sickbays will receive upgrades without having the nodes and upgrades unlocked. In this case the upgrade costs are not attached to the sickbays at all. They seem to draw power and function normally. This may be recreated by loading saves that have already unlocked sickbay upgrades, then going to a different save.

This is due to a bug in the stock upgrade system, where unlocking some upgrades at any point and hovering on a part using it in the editor part list will unlock them in any save that you load after that. There is a [partial fix](https://github.com/KSPModdingLibs/KSPCommunityFixes/pull/63) for that in KSPCommunityFixes, but that specific issue is a fundamental flaw in the stock implementation and will still happen occasionally.

Note that since the RDU/TV doesn't use upgrades anymore (but instead the built-in tech limitations of the configure module), this shouldn't apply anymore in that specific case.
