### ISSUE TITLE
uggestion]Long-term experiments tweaks

### ISSUE THREAD

**Issue by Empiro3** [Kerbalism/Kerbalism#856]
I've noticed that a couple of long-term experiments could use some tweaks to enhance playability:

**LEAVE:**

Requires visiting another body with Kerbals. This experiment is 1y+ but allows biomes in both low and high space and an inclination close to 45 degrees. For a planet like Duna, this means that you'll probably fly over 12 different biomes and never fly over the pole biome. The experiment will take dozens of years to complete fully (some of the smaller biomes will probably take hundreds of years) and net you a ridiculous amount of science. You'll also never be able to complete some biomes since you'll never fly over the poles.

_Suggestion: remove the biome part of the experiment. This experiment will still take 2+ years to complete around any planet (space low/high), but net you a more reasonable amount of science and take a more reasonable amount of total time._

**BEEP:**

Basically the same issue as above, but on a scanner. This experiment is 18 months and space low biomes. It doesn't have any orbital requirements.

_Suggestion: to differentiate it from SITE / MITE which are biome experiments (but with much more shorter timescales), make this experiment non-biome, but with a polar orbit requirement._

**Infrared Telescope / SENTINEL**

The experiment data rate is 1.25 MB / s. The fastest transmitter in the game is around 550 KB/s, so no antenna in the game can keep up with the data being created, even at maximum speed. Since the experiment also takes 25 years to run (note, the comment in StockExperiments.cfg says 12 years, but it's actually 25), no data storage device can store even 1% of the data produce, even with all the upgrades. As a result, you'd either have to wait more than twice as long to complete the experiment, or send up a probe every few weeks to fetch the data down.

_Suggestion: reduce the data rate by 1/10. This allows midgame antennas to also transmit the data produced._

**Comment by gotmachine** [comment]
The whole point of those long running experiments is to provide a steady stream of science for a very long time.

Beside, many Kerbalism experiments aren't really designed to be completed in one go (or at all), the goal is more to encourage launching multiple missions concurrently in multiple places / situations to have a steady income of science over time.

**Comment by bristowrichards** [comment]
To @Empiro3's point, I think the design philosophy here runs contrary to how other Kerbalism experiments are designed. The length of an experiment should the advertised length in `duration`, more or less. I get that the actual length of a data (non-sample) experiment can be extended through diminished transmission rates. The bottleneck of transmission rates makes sense as a factor that players can consider for long-range interplanetary communication, as they must consider what tech, electricity, and experiment resources they have as they design a craft and a mission plan. But for something within orbit of the home body, it doesn't make sense to face data transmission bottlenecks as an "intentional" design approach to lengthening the experiment. 

In `KerbalismConfig\System\ScienceRework\Tweakables\StockExperiments.cfg`, the following snippet describes the Infrared Telescope:

```
size = 289386462      // humongous data scale, reasons below.
value = 440           // 20 times the value (reason below),unchanged situation/biome mask. limited to kerbin high orbit only.
duration = 230083200  // 12. yes. 12. (years if it's unclear) - reason - hubble has been operating for close to 30 years at this point, and still provides invaluable data. This should serve the same function in ksp
```

If you want the experiment to last twelve years, why would the data generation rate far exceed any of the antenna configs Kerbalism provides? Why not remove `duration` from _all_ experiments and only use size as a way to lengthen the implicit duration of an experiment? If the intent of the IR Telescope experiment is to last as long as the Hubble telescope, the `duration` parameter should reflect that, and the `size` parameter should be balanced to allow a player to actually be able to plan for that goal with the tech they have, as the current approach is "the duration of this experiment cannot be discerned from it's duration description within the part description or the Kerbalism science log description, you kind of just have to figure it out on your own." 

I'd love to work on a PR for this, too - I don't mean to just complain! I just think this particular experiment causes self doubt for Kerbalism players who are trying to plan based on the experiment parameters, when the current setup is actually requiring the plan on an implicit combination of parameters, which is less clear from a user perspective and (appears to be) less unified from a design perspective.
